[package]
name = "sync_msteams_jira_comments"
version = "0.1.0"
edition = "2024"

[dependencies]
adf2html = "1.0.3"
anyhow = "1.0.102"
axum = { version = "0.8.8", features = ["macros"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
base64 = "0.22.1"
chrono = { version = "0.4.44", features = ["serde"] }
chrono-tz = "0.10.4"
envconfig = "0.11.1"
futures = "0.3.32"
hex = "0.4.3"
hmac = "0.12.1"
html2md = "0.2.15"
regex = "1.12.3"
reqwest = { version = "0.13.2", features = ["rustls", "cookies", "form", "gzip", "http2", "json", "multipart", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = { version = "1.50.0", features = ["full"] }
tower = { version = "0.5.3", features = ["make"] }
tower-http = { version = "0.6.8", features = ["fs", "compression-gzip"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
uuid = { version = "1.22.0", features = ["serde", "v4"] }
validator = { version = "0.20.0", features = ["derive"] }
